k3s_token: ENC[AES256_GCM,data:4dYcWAymEjYA/A6xGpAuLNrwbDiil1iBA3WokLd67WQybFxxPeZP484SzFuJoVGcb21Hy6KfBZRkkrDz6taWyBPtM9jZoEUYGyk/3qJFS9ovys9QoqMOXGdbnVqa1h2OTHG1IN58uF6LHHYO,iv:Z1ILcamyYlXgZzQIYslCfcOSBiEO7wPuDRUe4vpbQJo=,tag:Pi7zfiV+Ufqke2igNjuttQ==,type:str]
sops:
    age:
        - recipient: age1vsjjdkgrv72tr3uftryj2szt3n0xk8h3ce54kzyfsmxtymxu6s4qgu5yuk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UXozMkM2c1FRclBtc3U2
            d081SGZLbkhocFFleGprUS9RQWlpakRCSGcwCit0SEdXZ043S1ZBWUovVDZhOGxV
            eUJyTTl0QStLZzg1YVFvNjRQQ2lDUEkKLS0tIEJXOFZzbnVwSDdHVEVRTTQvQzRH
            VFBIa3ZLTHB1dk05MHZ4SmxQanVSYTgKkGpCLmt15NCgbGK+VmBnAe8D2xmDINK8
            ZULSujMykeycwfESaG6TaHYpgl9Ve8CdnHYXtq5Oh0pN/BIGVwwWwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16lkhqtnle3z62gy0tk9x4tn3w43st2cnvdpl8r84xpzkn2f7jv8qxl5a9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQTRHSU5Bdnc3b1JXNXRl
            eGdnTkdBalN3ZHZnbHV3dVdob2ZuY0lpSkVvCklIZmRZeUdIa3g1MDkrTTRzYXpR
            OWZVYno3ck9rQ3Nrc2huVkhwWmkxT3cKLS0tIEFYb050U2t6ZFl6aFZ5VEtWMWsy
            eFluTlpUWWFSZURMZWRYdFlTelRJc1UKkS+8FYaD4+jOQlhyS6QxHT0l2AK/grAp
            Hb9IgBw8sXX6DNIzYIetw5aPQuhSZjKPc9BKe11VpHR8HTfbXTZRbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age199ny6lhask8zc65auwygqhj0svjkpp5kr7lhht8hvj947vaclecqrt4yg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSGhFSUVmSlNvMFEvZVJN
            L1BmREZOQXlkTkpTekZGMitSOEMwOXBrWVJ3Clp0Vzgram83N1NKUmxMblB2Rk5j
            UHJiSGZtUWNVMmhBekRrL2dLdE15OFUKLS0tIDBwemxVOEU0bTkrODkxTkFSNmZR
            MGpYbForMmFuSGJvRmpLUTRkeEFpQkkK0u+ZrgmFHn5xmuQkyH5y6/3PI/QNY86x
            WWTU5PYobG5545CVzEBRwoXMZZmrkOsQBvWdh4lSN0e/xLBrH2ejCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pc0qdk5d2fen55cstvtch588wcqgzemgavlsvsc5dm0r4uw00vrq297et7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjdDbUwwNEJSRmpIaFIv
            TWJFempSUDJWVHFiV2cvejhFbVIrT1dFMGhvCldwWGkrU0lHREJ1THNhcTlqM3gy
            czNFdlgxbEZBVlo5RHBsK0szbkZUTGcKLS0tIElGMkFuZkVBTmJsVXdCZXBYeVZ4
            bEJsY1hrdi9nL2REbkxMcWQzeThqMmsKAvXSr3SSAvP/hoBhVBgRhoQLmKIdQ7RW
            gCFhNnK+alA7J2Bq7RFE98Rz4HAt6qWu2m6izY91dLq7NMWc5wxbeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vmnnywhflwymjcgllmp5sgf05dn3qvamd2ylhxquwcuvlrm8ma3sc882mp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRjJsV21UMmVMUysvRXU2
            RWlsVk01MFZFUnNSODJIRzJURWdiVTc3d1dvClpRS2x6aWNNTk9BKzY0akNxNjV5
            OFNxcDM3YzBvcUZYQXUzcDlvTlc0eTgKLS0tIGt3L2ZsVEY3YTZFSTlUTWNRUlV0
            TmhaeHFaclJteERuUllsY3hCVE5XWXMKw0ofnwe4WYL9Fl/kadkJaI1Ed5YWix0x
            VVDHw9h4az0H7bw7I9QrWoLq+J7zkHgh2hm+oFm+0C7rFwJ4n7m7sQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nfkkq86jk3yhhzgk3jt0kjzfpzv4qee3uheellawzgrmd296gczqa68yt7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UkVlbE4zc3JlakJ2VDhr
            RUZRbDVVcEJ4ZGNyY3JZUjFaWTQxRHo1RVdZCjlkT29CV0REaDRRK0xCa2U5ZW9U
            a0ZxVjBwWkZvb1IrZGpKaXUrekJ0TDgKLS0tIGdBK3Uzb3VQWHVjRXZOSzNKaHY3
            UTBEdVVNU2dxV21RR253VG9VSytDZlUKNo5BMRD1JvliMB2YSUKqoPOoeGeUp15P
            /CugAd1jut9uUT1XBu+P/FTchhHpqdfJo2PHRD2Dc2VCU+7/OQXI5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zm36rngg07hrm8nj3r8wj5ucz85njxzfwsxftsx3gtdmzkgw3peqh8vf55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeU9BNFNFaC9LOThCVkJC
            ZmhXZjl3Z2FmSUdlREhNMTFTaEJka1pZNzI4CkZ4WGI5THFnWHk0dEZka0VHcXU0
            OXpGcEdSZGVNei9wa2M4d1BudlJQSzQKLS0tIDZuRGdRNkhDenVUbk1JcERraUE5
            SXRLRkNvWm9wcVFTdllwZHdUSng1UlUKo9oQbpTI9QInCmZWCqvONzvIt9NFOvZW
            G5KxrQf8Ed0XUSlPsVunDa/PzFwBbTK6tcY2yGN43zBEZ4uDvoKdjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x4x5ujnd9em23jhs53lgwqcmw9t6hx64xtdt3x0u4n66fsuygf9s4njjla
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dkxMN25aTGhhMERKTlVt
            dUZxYWhOdk1MUGFnc0VsWnJKTUV0V2ZSTTNFClVOVS9pREM2WlQrY1hqYWZDQi9x
            WHNLbmo3RXU0VmR0RGNGaEV2Zmw5Z2MKLS0tIHZqbVZxOXd2QzBRM0g5ZS9QcFEv
            TnVPWHNtSmZxdGk0aUh5Q3VhN3F4NU0KX4alD7TbvmqYaGfOfXtlhtV8gD6lZM91
            1LT/fzJe66cEuYUzud3VseFUDlG4/d1L/mpddIYfDRcYTPsA9CoTQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s6rx9whkkf35t7qaju9vvla8tl2nstt0drx722ca4qadqfx66g0slxyxd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQnIvTnA3UHVaTDM3VjNZ
            ZFFTclVHSU5tbTdTMndHTkZIRU9pSjNuL25RCk5jN0ErR1BWa05QWFV5R1hLbkwr
            blN5ckVXSTBIU0JKejB4RDFvaHhUSDgKLS0tIFpNbFpONGdHdFBZS3ZycnRyUi85
            alVnYkdYUC8yRmFhQ1JVbklvd1AzSjQKgiV+GCKZGvvsdyhFk7zV3xuYqr46+6PA
            iEAVU5gzrerOLQ9UnIKDAvmwze3epc7LZ4aTvSUjYCaYbQrZUukTQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T18:46:55Z"
    mac: ENC[AES256_GCM,data:UiDM21o5P4JU8j76Kz0AMvE8EenH+yKGpzmTmI2MkPGR2DSWv4WGB2HUi+K2ZL5S493tkFXZysiss5AbWcjfkS2qf/Fr8MbUe4JLhdzm8Y2RqFyHQ42gERe2KZWANIdtGRgn6IF+ELCTe5GJ4KE3fCF1+DwVe34ZcLAaolOR0ak=,iv:16T7yk1++no7KmzzmBylknuXD8Mw5uxEaQ3rsxEMGhQ=,tag:SZGGbyJ/YtwEJ0ORwrd6Eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
